version: "3.8"

services:
  app:
    container_name: app-react
    build:
      context: .
      target: development
    volumes:
      - ./app/financas:/app
    ports:
     - 3000:3000

  app_producao:
    container_name: app_producao
    image: app_producao
    build:
      context: .
      dockerfile: Dockerfile_producao
      target: producao
    ports:
      - 3000:443